### ISSUE TITLE
Unexpected error in DevTools

### ISSUE THREAD

**Issue by piecioshka** [dogescript/dogescript.github.io#6]
Hi!

On your page (https://dogescript.com/news/hello-bloge/) some error is occured.
Can you fix this?

**Comment by piecioshka** [comment]
Page https://dogescript.com is down.

**Comment by AnEmortalKid** [comment]
Yeah I think whoever owned it stopped paying for it. Lemme see if I can
snag the domain :) and I can get vzorpm to put the rehosted  site on.

Thanks for reporting that!
